* Notes
[[https://youtu.be/NNnIGh9g6fA?si=iyQXAILtbjMrlNyk][lecture]]
- Sometimes, whatever going on in your body affects what happens in your head
- Sometimes, whatever occuring in your brain determine what happens in your brain
- When youpay too much focus to categories, you can't differentiate(or underestimate)
  two facts in the same categories
  - example, we have differentiated visible light rays into VIBGYOR
    but in reality, it's just a continua of wavelenghts, so if we are
    encountered with two slightly different wavelenghts of let's say red
    we would notbe easily able to differentiate between them.
- Similarly, we overestimate two differnt facts in different boundries however close they are
  - example, cutoff marks, one markis not that much but getting above
    or below that boundry drastically decides your future
- Whem we pay too much attention to boundaries, we can't see the bigger
  picture as we are more focused in categories
- Wellesley effect
- Wee get stressed by the inevitability of our mortality
** Evolutionary biology
*** Behavioral Evolution
- traits(in population) changes over time -> speciation
- traits are heritable, they have variability, some of them are more adaotive than
  others. Also, overtime random traits can appear(mutation)
**** Natural selection
Process that results in the adaptation of an organism to its environment by
means of selectively reproducing changes in its genotype [[https://www.britannica.com/science/natural-selection][source]]
**** Sexual selection
Evolution of certain conspicuous physical
traits—such as pronounced coloration, increased size, or striking adornments—in animals may
grant the possessors of these traits greater success in obtaining mates. From the perspective of
natural selection, such increases in mating opportunities outweigh the risks associated with the
animal’s increased visibility in its environment. [[https://www.britannica.com/science/sexual-selection][source]]
**** Individual selection
Animals does not behave for the good of species.
Animals behave for passing on as many genes as possible.
Sometimes, a chicken is an egg's way of making another egg
**** Kin selection
Natural selection favours a trait due to its positive effects on the
reproductive success of an organism's relatives, even when at a cost to the organism's own survival
and reproduction. Kin selection can lead to the evolution of altruistic behaviour
  - Animals can keep track of kinship
  - Evolution selects for organisms cooperating with their relatives
**** Rock Paper Scissore scenario (an evolutionary stalemate)
Each organism has the potential to harm one of the
others but doesn't do so because the overall impact of those actions would hurt the original
organism.
***** Evolutionarily stable strategy (ESS)
A strategy (or set of strategies) that is impermeable when
adopted by a population in adaptation to a specific environment, that is to say it cannot be displaced
by an alternative strategy (or set of strategies) which may be novel or initially rare.
**** Cooperation
Behaviour whereby an organism acts in a manner
that temporarily reduces its fitness while increasing another organism's fitness, with the expectation
that the other organism will act in a similar manner at a later time. The concept was initially
developed by Robert Trivers to explain the evolution of cooperation as instances of mutually
altruistic acts. The concept is close to the strategy of "tit for tat" used in game theory.
  - We are more attuned to picking up cheating than a random act of kindness.
  - Until you're not putting more into i than what you're getting
  - Nash equilibrium
**** Game Theory
Branch of applied mathematics that provides tools for analyzing situations in which
parties, called players, make decisions that are interdependent. This interdependence causes each
player to consider the other player’s possible decisions, or strategies, in formulating strategy. A
solution to a game describes the optimal decisions of the players, who may have similar, opposed,
or mixed interests, and the outcomes that may result from these decisions.

Studies have shown that brain centers responsible for pleasure light up during times of stabbing the
other guy in the back and during times of cooperation. There is a pronounced gender difference as
to when these areas are activated. 
***** Tit for Toe(TfT)
- Best Strategy
- Drives all the others into extinction
- Vulnerability of signal error
| Rounds Rounds | 1 1 | 2 | 3 | 4 | 5 | ... |
|---------+----+---+---+---+---+-----|
| A       | o  | o | x | o | x | ... |
| B       | o  | o | o | x | o | ... |
|---------+----+---+---+---+---+-----|
If A cooperated in the 3rd roundround but due to somesignal error, B percieved
it as cheating. In the 4th round, acc to TfT, B cheats and A who has been
cooperating for all these rounds gets cheated and next round A cheats. B sees
he's been cheated twice so h cheates back and we get ourselves into a seesaw
pattern for the rest of time.
***** Forgiving Tit for Tat (fTfT)
- If we go in the seesaw loop of TfT for 5 rounds, we will cooperateand it
  will get things back on track
- Vulnerability of getting exploited
***** TfT->fTfT
- We shift from TfT to fTfT after developing trust
***** Pavlov
- If I get rewarded, i'll do the same thing again
- If I lose, I'll switch to otherstrategy for the next round
- It exploits
***** Example in nature
Vampire bats are up next. The mothers suck the blood out of other animals, such as cows, and then
bring the blood back for the kids. They are social animals and will feed others' offspring as well.
Research has been done in which mother vampire bats were captured and had their blood sacs filled
with air so that it would appear to the other bats that they had a lot of good blood to share. When
they returned to the nest and did not share, others took note and were then didn't help the
research bat's offspring the next time they returned with blood food. 

Stickleback fish also engage in tit for tat strategies. As does the Black Hamlet Fish, which is also
capable of changing its sex. Tit for tat strategies are used by this fish when the other mate doesn't
carry his or her load by being the female as often as the original fish (higher costs).
***** Limitation
Reciprocal social altruism also includes consideration for other domains of behavior, so an animal
may be worthless in one area but valuable in another and studies have shown that social groups
will accept and value this approach. He mentions examples of naked mole rats and lions.
**** A behavioral analysis based on skull size
I'm too lazy to type allthes3 notes so from here on i've used the notes from [[http://www.robertsapolskyrocks.com/][here]]

|----------------------+------------------------------------+-----------------------------------|
| Behavior             | Big Male, Small Female             | Small Male, Small Female          |
|                      | (Tournament species)               | (Pair bondng species)             |
|----------------------+------------------------------------+-----------------------------------|
| Aggression           | Tournament species are more        | Pair-bonding species are less     |
|                      | aggressive.                        | aggressive.                       |
|----------------------+------------------------------------+-----------------------------------|
| Variability          | TS has a high level of variability | Relatively similar levels, 1-2 on |
| Reproductive Success | with top few having most success   | average.                          |
|                      | 95% from 5%.                       |                                   |
|----------------------+------------------------------------+-----------------------------------|
| Female choice        | Good genes for offspring - big,    | Resource and parental skills.     |
|                      | strong. Thats all she's getting    |                                   |
|----------------------+------------------------------------+-----------------------------------|
| Lifespan             | Lower-more fighting, aggression    | Longer, similar to females        |
|----------------------+------------------------------------+-----------------------------------|
| Parental behavior    | Virually none                      | A lot                             |
|----------------------+------------------------------------+-----------------------------------|
| Twins                | Rare                               | More common                       |
|----------------------+------------------------------------+-----------------------------------|
| Ababdonment          | Rare, male won't care for          | More common, males will take      |
|                      | offspring                          | for the offspring                 |
|----------------------+------------------------------------+-----------------------------------|
| Examples             | Baboons, chickens, peacocks        | Marmosets, tamarins               |
|----------------------+------------------------------------+-----------------------------------|

Humans are right in the middle.
*** Behavioral Evolution II
Man is not the only species that kills for non-predatory reasons.

Infanticide is found within groups of langur monkeys, lions, vervet monkeys, mountain gorillas and
other species as well. Initial attempts were made to dismiss the events as abnormal, with a variety of
reasons to set aside the behavior as psychopathological but not typical of the species.

But then biologists began noticing patterns. It tends to be adult males doing the killing. The actions are not random; the
infants are the offspring of other males. It's a competitive strategy that reduces the other guy's
reproductive success while improving the killer's since the female no longer has anything to mother
and can now move back into the birthing cycle and have his offspring.

There is a formula for this - competitive infanticide occurs when the time between births by the
mother is shorter than the average reign for the top male. So the competitive infanticide is there to
ensure that he doesn't miss out on the chance to breed with the female when she's busy rearing her
offspring instead of mating with him. 

The most striking example of how this demonstrates that animals do not operate for the good of the
group is that of mountain gorillas. Their numbers are dwindling with approximately 600-700 out
there in the wild but they continue to kill their own despite it being against their best interests.

It is, however, highly unlikely that Ishmael would engage in this foolish behavior...

However, when the male replaces a relative, the infanticide is checked by the element of kinship
selection and the evolved behavior of supporting, not destroying, the success of relatives. 

Females have developed responses to the infanticide. They may spontaneously abort the fetus
(rodents), miscarry after being harassed by the new male (wild horses) or even go into pseudo-estrus
in which they give off all the signs and even mate with the new guy but without actually giving up the
original fetus. 

Females will also physically defend their offspring, with the most menacing being the maternal
grandmother who has past her prime but still has a genetic stake in the matter. The mother will
defend, but not to the point of serious injury. As she ages, her defense will be more vigorous. (Of
course these are general patterns and an aggressive male is not guaranteed that things will turn out
well for him.)

Kidnapping among savannah baboons is more likely to be seen when the aggressive, high ranking
male has been in the troop for a while than when he hasn't since some other baboon's offspring
doesn't make a compelling shield. 

**** Dominance hierarchies
In essence, having males is
a "risky strategy" in a tournament species because 5% of the males get to produce 95% of the future
offspring, so the odds are that a male will not get to mate well. Females tend to mate regardless, so
having a female will tend to carry the genes onward at a higher rate. Thus higher ranking females
show a greater tendency to give birth to males while lower ranking females have a greater tendency
to give birth to females. This is not a choice, but rather reflects some gradual adaptation that's
resulted from the males of top ranking females getting to pass on their genes while the lower
ranking females' male offspring did not but their daughters did. However, dominance among the
males is not based on nepotism, it's based on strength and power, so a male can ascend if he's able
to. And the male offspring of a top ranking female may be entirely unsuccessful. My sense is that
there isn't a lot to be gained from this section as it's speculative and, of course, the females aren't
really choosing to have a male or a female baby; there's simply some tendency that has enabled the
offspring of top ranking male-female combinations to be more likely to produce a male. This notion
leads into an upcoming topic, which is intersexual competition.

The bias toward more females during times of ecological duress connects directly to the metabolic
demands of males being higher than the metabolic demands of females. The tougher it is on the
mother, the greater the odds of the fetus not surviving. 
**** Intersexual competition
Intersexual competition reflects differing interests in the future reproductive success of the female.
In tournament species in which the males migrate, they care little about what happens to the female
once they are gone and so aggressive elements are sometimes found within their sperm. These
elements help increase the odds of generating a successful pregnancy and set the fetus up to be
more metabolically demanding. Females, on the other hand, have evolved ways to neutralize these
elements as they are costly and dangerous. 

Imprinted genes are genes that have different manifestations depending on which parent they came
from. In classic Mendelian genetics, a combination of Aa and AA treats the A's as similar, but with
imprinted genes it actually matters whether the A came from the father or mother because the gene
will behave differently. Through the process of methylization, the gene's behavior will be altered
based on its origin. If you get it from one parent it will be active, if from the other it will be silenced.
When you look at imprinted genes that are active if they come from the father, they all tend to be
genes that promote fetal growth. If from the mother, they tend to slow down fetal growth. For
example, one of the genes codes for insulin like growth factor. Not hard to see how that fits in. The
female's version makes for a less responsive receptor for the insulin like growth factor. Another
example is choriocarcinoma, which is a cancer of the uterus that can happen if the male's sperm has
aggressive growth factors and the female has no counterbalancing genes; this leads to unchecked
growth which is bad. Pregnancy hyperglycemia is another example as the fetus is trying to get lots of
sugar from mom but mom may have an active gene that checks that (hypoglycemia will occur if she
does not). These types of imprinted genes are not typically seen in pair bonding species. Humans are
again right in the middle. 

Next up is the fun topic of...sperm competition? Yes, research into fruit flies shows that another
strategy that's out there is the sperm carrying a toxin that kills off other males' sperm. Sadly for the
females, the toxins are also potentially toxic to them. Thus we see females have evolved ways to
counteract this. 

Exogamy impacts the behavior of animals as well. There is variation in who leaves (females in chimps
and gorillas, males in baboon troops) and that influences what happens within the group. For
example, chimp groups can be highly aggressive and even genocidal toward other groups
("outsiders" or "them") because the males are all related by kinship ties and thus get along much
better than they would if there was male exogamy.

**** Group selection

One of the scariest things in the world is when all the males in a given group start getting along
really well with each other. Aggression toward the others often follows. 

This relates to military techniques that aim to create a sense of kinship among the troops. This makes
them a band of brothers that will cooperate with each other, though it can have divisive effects as
well, such as was seen in the Vietnam War, because the group may agree to disagree with orders and
commands from above, the hierarchical other.

- Founder Effect
  A bio-geographic (or other) event occurs that separates out a subset from a larger group. This
  smaller subset soon becomes more inbred than the larger whole, simply as a by-product of being a
  smaller group. This translates into having a higher degree of relatedness, which introduces the
  whole business of kin selection. Because these guys are more closely related, they will work together
  more as a group and will end up outcompeting the original group members when they are reunited.
  
Another scenario is demonstrated through the example of two chickens, one that's highly aggressive
and one that's more laid back. When competing one on one, the more aggressive chicken will lay
more eggs, but there's the drawback in which a group of aggressive chickens will harass each other
and thus impair their own breeding while the calmer group will lay more eggs because as a group
they cause less grief for each other.
*** Criticisms
The first criticism rests on the notion of heritability and the associated notion that the behaviors are
genetically received, inevitable and produced. The next notion is that of adaptiveness, which
suggests that all behaviors have evolved because they are adaptive (beneficial). The third principle is
that the changes are gradual. 

The molecular view challenges the notion of heritability. While the evolutionary biologist argues that
the trait is commonly seen among groups and has emerged because it is inherited and beneficial, the
molecular folks say show me the gene, establish the direct connection.

Adaptiveness is attacked as the adaptationist fallacy. Everything is reduced down to a just so story in
which the best story wins. He notes that to honestly assess it, you must keep the context in mind.
Squid aren't so great as swimmers compared to fish, but they kick butt compared to mollusks, which
is where they started. Nevertheless we have the concept of spandrels (courtesy of Stephen Jay Gould
and Richard Lewontin), suggesting that some evolved elements just came along for the ride. 

These spandrels would be decorated, but for all that they weren't put there for adaptive purposes.
They are simply inevitable when arches are brought together. As Francois Jacob put it "Evolution is a
tinkerer." 

The theory is heavily saturated with elements of competition and outcompeting the others at every
level, with the winner being, by definition, the best and most worthy and most fit. All of this fits in
with rather nicely with the world view and SES of the people advancing these arguments, each of
whom was a Southern white male. 

On the other hand, competition may not be the most important element. Russian biologists viewed
the issue from a collective viewpoint and had a greater respect for the impact of external elements,
such as the environment. 

Gould and others suggested that gradualism was possibly a flawed concept. Instead they suggested
that punctuated equilibrium makes more sense. In this scenario, most of the time nothing is
happening and there isn't really much impact from all this competition stuff. Then a genetic change
of some sort occurs and a massive change follows and then things return back to normal. 
**** Politics
Politics comes into play as well, with issues ranging from male domination, sexual aggression, social
stratification and more and the question of the extent to which these are a reflection of natural
order. 

On the other hand, the gradualists were Northeastern Marxists. And the world they want it to be fits
smoothly into the notion of dialectical materialism. 

** Molecular Genetics
*** I
**** Proteins
Genes as molecules, genes as information, genes as DNA. Here we have proteins emerging for their
importance in the structure of cells and cellular activity. Proteins hold the shapes of cells together,
they form messengers and hormones, they are the enzymes that do all kinds of important stuff;
proteins are the workhorses.

So what codes for proteins? This is where genes come in. Genes specify (code for) proteins. Proteins
are built from amino acids, of which there are approximately 20 that commonly occur. Each one has
to be coded for with a different DNA sequence, a different DNA sequence of 3 letters (3 nucleotides).
He notes that in the process DNA first specifies a code string of RNA which then specifies the protein
construction (amino acid string). Thus if you know the DNA then you will know the RNA which in turn
gives you a sense of the amino acids which will form the protein and knowing that informs you of the
shape of the protein (different amino acids vary in their attraction toward water and these levels
influence the ultimate shape) which clues you in on the function of the protein. That is the critical link
from the DNA to the function and the notion of a behavior being genetically controlled. 

Proteins fit into other molecules like a LOCK and KEY! This is the whole world of hormones and
neurotransmitters fitting into their particular receptors. 

He notes that prion diseases are an exception to the hydrophobic/hydrophilic structure of proteins. 

Enzymes are important because they catalyze reactions. That is they cause reactions to occur which
on their own would be unlikely to happen. A simple way of looking at this is to think of it as bringing
things together or separating them, as appropriate. Virtually every enzyme is a protein. This affects
cellular activity by influencing the opening and closing of ion channels. Ion channels connect directly
with the cell's decision to act or not. 
**** Central Dogma
Francis Crick is credited with establishing a central dogma of genetics - DNA codes for RNA which
codes for proteins. Sapolsky focuses the listener on a subtle element of this dogma, which is that DNA
is ultimately in charge, sitting around and deciding what will happen and when, and then releasing
the instructions that become the RNA to protein chain. Surprisingly, DNA isn't always in charge.
Viruses are mentioned as an example. Viruses are basically snippets of DNA that get into a living
organism and hijack its DNA, taking over the plane and directing where it goes, making it function for
the virus's desire. In the 1970's viruses made of RNA were discovered. The pathway is facilitated by
enzymes which convert the RNA into DNA and start up the whole parasitic process. Accordingly, these
are called retroviruses because they are reverting from RNA back to DNA. 
**** Mutations
Mutations are important because they can alter the orders from DNA. A micromutation occurs when
one letter within the DNA sequence is accidentally miscopied. Pairs of triplets (amino acids) are coded
for by the DNA. This is a connection of three base pairs. So we can have a change in one of these
letters which may impact the ultimate shape and function of the amino acid that is created.

There are three basic types of alterations. First is a point mutation, which consists of one of the
letters being changed into a different letter. This may not matter because of the limited number of
different amino acid combinations. There are four different letters (nucleotides) and three letters
needed, so we get 4x4x4 or 64 different potential combinations, but there are only about 20 amino
acid shapes, so there's overlap in that shape 22 GAU may be similar to shape 43 GTU, so the change
from A to T may not significantly change the shape (please note that this example is an example for
understanding and is not based on a specific shape 22 or 43). 

For example: "I cdnuolt blveiee taht I cluod aulaclty uesdnatnrd waht I was rdanieg. The phaonmneal
pweor of the hmuan mnid. Aoccdrnig to a rscheearch at Cmabrigde Uinervtisy, it deosn't mttaer in
waht oredr the ltteers in a wrod are, the olny iprmoatnt tihng is taht the frist and lsat ltteer be in the
rghit pclae. The rset can be a taotl mses and you can sitll raed it wouthit a porbelm. Tihs is bcuseae
the huamn mnid deos not raed ervey lteter by istlef, but the wrod as a wlohe. Amzanig, huh ? Yaeh,
and I awlyas thought slpeling was ipmorantt ! Tahts so cool !

Changes in the 1st or 3rd nucleotide (letter) may also be of minimal significance as the amino acids
have similar shapes so a minor letter change may only result in a minor shape change that produce
a minor change in results but does not dramatically change the functioning of the amino acid. 

I will now do this.
I will mow do this. 
I will not do this.

However, there can also be a point deletion. This consists of a nucleotide being deleted. In classical
genetics a deletion mutation has dramatic effects and is a big deal.

I will nod ot his.

The third type is insertion mutation.

I will now ud othi.

Deletion and insertion mutations tend to have big consequences. 
***** Phenylketonuria
The takeaway is that these mutations change how well the protein does its job. For example, there's
a chemical in the body called phenylalanine which has its uses but if it builds up to a high level it
becomes toxic to brain cells and results in mental retardation, brain damage and seizures. There's an
enzyme (made of proteins) that converts it into something safer. Now the scenario is that you have a
mutation in the gene that codes for that enzyme. As a result of a micromutation, the enzyme no
longer does its job. The phenylalanine then builds up in the body and creates the disastrous effects
noted above, laying waste to one's nervous system. This is Phenylketonuria (PKU) disorder. This is
not a minor change; it will rapidly destroy the person's nervous system. 
***** Androgen Insensitivity Syndrome
Another example involves a hormone being changed by a mutation. Imagine a daughter that is not
hitting puberty when her other classmates do. At 10-11 some are experiencing changes but not her.
She continues to age and does not reach puberty. Since she's falling behind you take her in to see the
doctor. Eventually the doctor is going to sit you down and explain that the reason why your daughter
has not started menstruating is that you don't have a daughter; you have a son. This kid suffers from
TFM, testicular feminization syndrome (also known as Androgen Insensitivity Syndrome). At the
chromosome level, they are male (XY not XX). They have testes, but they never dropped or developed
normally outside the body. The testes make testosterone. Nevertheless, you get a female phenotype
with female external genitalia. This results from a mutation that changes the shape of the androgen
(testosterone) receptor, making it insensitive to the androgen's attempted effects. 
***** sex change
Another example relates to a disease found among two populations - one up in the mountains in the
Dominican Republic and the other population in the mountains in Papa New Guinea. In this disease
there's a problem with the enzymes that make testosterone. So what happens is that there's very
little testosterone having any influence - the levels are too low to take effect. So the kid is
phenotypically female with female external genitalia. Next when puberty hits the brain tells the body
to start producing testosterone. The body does so and while the levels don't go up as much as they
would in a normal male because of the enzyme, they go up enough. And the poor kid switches sex. 
***** Benzodiazepines
He mentions benzodiazepines (synthetic) are up next. He mentions that differences in the amino
acids will subtly impact how these guys fit into their receptors which will in turn impact the
individual's level of anxiety. This example points to the variance among people that minor
differences in genes can create.

He transitions into brief comments about rats that were bred to be high or low anxiety and then
notes that this moves us away from "them and their disease." This foreshadows the lecture on
individual differences, a lecture that is surely among the best psychology lectures ever as Sapolsky
brings a startlingly, empathic and eye opening perspective to the issue of individual differences and
makes it crystal clear why it isn't "them and their disease." (Watching that lecture and his discussion
on depression will place you ahead of 95% of the population in understanding individual differences
and psychological problems. Sapolsky simply rocks.)
***** FoxP2
Foxp2 has something to do with language. The discovery began with a family that displayed a
mutation in the Foxp2 gene and had a language anomaly of some sort (motoric or symbolic - that
was the debate). This is potentially significant because versions of Foxp2 occur throughout the
animal kingdom. Birds, rats, apes, people...and in all these places it has something to do with
communication. Curiously the differences are small until you get to humans and there we see a
whole bunch of changes when compared to other members of the animal kingdom. So the major
difference in language capability may be the result of continual evolutionary change in the base
pairs of the Foxp2 gene. 

An experiment was done a few years ago with mice in which they knocked out the mouse version of
Foxp2 and substituted the human version. The mice began to demonstrate more complex language
expressions. 
**** Positive and Negative Selection
Ok, so there are 64 possible combinations that code for 20 amino acids. Say you look at a mutation
and 40 of the combinations have no impact. In this case we have a standard mutation rate with
2/3rds of the changes not impacting the formation of the amino acid and 1/3rd changing it. Contrast
this with a scenario in which you examine a mutation and find that 99% of the differences in the base
pairs will impact the amino acid's formation. This is an echo of a very strong advantage or adaptation
- there would have been positive selection for this trait. It's not general variation or just hanging
around; it's been picked. 

Alternatively if 99% of the mutations have no immediate impact this is a stabilizing gene in which you
do not want to mess with its function (it's strongly set against any kind of change, which indicates
that change is really bad in this area).

The changes in Foxp2 are positive changes.

Ok, so here's the idea. If 99% of the changes impact the amino acid then we have positive selection.
If 99% don't, then we have negative selection. It works this way because the positive elements can
build on each other and changes in it can be beneficial while impairments aren't devastating (for
example, do any of us write like Marcel Proust? No, but we can still express ourselves poetically).
However, when 99% of mutations have no impact, it's a highly stabilized gene. For example, do any
of us have no lungs?
**** Sharing genes
Next up is the whole sibling chimpanzee percentage topic. You share 50% of your genes with a
sibling, but you share 98% of your genes with chimpanzee. What? This is about the level we look at.
For example, chimps and humans have noses, so that's a commonality when compared to a tree,
which only has a nose when it's in "The Lord of the Rings" or wandering around Stanford. However,
humans can have button noses, aristocratic noses, etc. which is a DNA difference but at a much more
specific level. 
**** Punctuated equilibrium
The carryover to the political element is that if every bit of the advantage or disadvantage that comes
from a mutation matters then it follows that every bit of competition (competitive advantage) also
matters. 

In the 1980's Stephen J. Gould, a paleontologist, and Niles Eldredge, also a paleontologist, came up
with a very different model. They challenged the gradualist model, arguing that instead there are
long periods of stasis where nothing happens and that the little changes don't matter much. Instead
when change happens it's rapid and dramatic. This is known as punctuated equilibrium. Gould was a
Marxist, though, so it's worth noting that this model fits in with the dialectic process (thesis -
equilibrium; antithesis - mutation; synthesis - new beings). Analyzing the fossil records shows long
periods where nothing seems to change and then suddenly there's a big change followed by long
periods where nothing's happening. This implies that the vast majority of the small changes aren't
that important and that the competition framework is incorrect and serves mostly to create an
illusion that nature has a massive hierarchy that's determined by competition when in reality nature
permits most varieties to do just fine, thank you. Continuing with the political theme, it's then noted
that it's mighty convenient that the competitive model fits in nicely with the environment that its
advocates come from and have benefited from. 

The first counter is that these are very different disciplines - what counts as rapid for a
paleontologist isn't really fast. 100,000 years isn't all that quick (and changes that occur a little bit at a
time due to competition over 100,000 years could appear rapid based on the starting point while
still being driven by each minor advantage the whole time). 

The next counter is that flesh and tissue do not leave a record in the paleontological record. A fossil
won't tell you what happened inside the brain (in the sense that minor advantages won't necessarily
manifest physically; anyone reading this likely has intellectual advantages over the vast majority of
your peers but is unlikely to have a gigantic elephant head that holds a bigger, stronger brain. It's
all the same from the outside.) All paleontology can study is forms, morphology.

The third challenge comes from molecular biologists who ask for the actual genes and evolutionary
mechanism that would create this pattern.

Sapolsky notes that when the last challenge was brought up in the 1980's the paleontologists didn't
have a good, evidence-based rejoinder, but that a lot of the stuff that's happened since then has
supported the notion of punctuated equilibrium.
**** Non coding DNA and and instruction manual
Next he moves onto DNA. When we look at a DNA strand, there are periods that code for genes
interspliced with large sections (95% or so is non-coding) that function as an "instruction manual."
The genes themselves are not always coded for in just one snippet. Often multiple areas on the DNA
will code for parts of the same gene. So you can have a section that codes for the first third of a
protein followed by a long stretch that has nothing to do with that protein. This is then followed by a
section coding for the next third. And so on. Each of these sections is called an exon. The in-between
stuff is called introns. People deduced and then discovered something called splicing enzymes. 

The splicing enzymes would come along and snip out the intron section so that the first third of the
exon connected to the middle third and the final third to produce a clear read-out. 

David Baltimore was the first to introduce the concept that this makes the genes modular and opens
the door to massive information within the DNA universe. Because of this flexibility, DNA would then
have the potential to abandon the original A-B-C model and create, for example, an A-C combination.
This will give you 7 different ways to combine these exons, which means there are 7 different
proteins that can result (pacing mutations of course). 

This is a massive deviation from the concept that one gene specifies one protein. Different splicing
enzymes can thus create very different results. The more they are researched, the more flexibility
emerges - different enzymes, splicing at different spots. So we have different items being created by
the same basic DNA original set due to different splicing enzymes being activated and activated at
different times of life (think Mr. Potato head as DNA and a child as the splicing enzymes - same basic
pieces, lots of possibilities). 

The instruction booklet part of DNA is all about when and under what circumstances to activate and
start and stop creating proteins. (For example, human growth hormone is released throughout life
but has peak periods.) For better or worse this means that DNA doesn't "know" what it's doing.
Instead it's a read-out that's under the control of lots of other factors. Among these are the
regulatory sequences upstream from the gene. These might be called promoter or repressive
sequences that promote or repress the expression of DNA snippets downstream. They are like
switches. And they are turned on when the right event (internal or external) happens. These events
are triggered by transcription factors. These might turn on single genes or whole networks in the
DNA. On the flipside, any given gene can have a whole bunch of different promoters that it's waiting
to hear from before it does its thing. 
**** Environment and transcription factor
So who's in charge? Whoever or whatever controls those transcription factors. Including the
environment. Which has something to do with genetic effects (shocker!)

So what qualifies as environment?

It could be something within the cell. For example maybe the cell
is getting low on energy. This could release a transcription factor that would result in the cell being
activated to take up more energy. 

Or it could be something from outside the cell, such as a hormone floating around in the
bloodstream. A hormone is a blood borne chemical messenger. Testosterone is used as an example.
It would float far and wide and have its effects and those effects would increase significantly when
the male hits puberty resulting in changes in lots of areas in the body. 

You could have a messenger from the outside environment, such as a scary sight or an olfactory
messenger, like a pheromone.

As a consequence of this, Sapolsky notes that the most interesting stuff with DNA now is not the
specific nature of the proteins but rather when it does its thing and what elements trigger it. 
**** Chromatin and epigenetics
DNA is covered, stabilized and protected by chromatin. And so there is a whole world of messengers
that inform the chromatin of where and when to open up and allow the transcription factors
through. Changes can also happen that will permanently impact the chromatin. For example,
mothering styles in rats have been shown to permanently change elements in the chromatin in areas
relating to anxiety. This leads into the field of epigenetics. Research with monkeys has shown a
change in one area impacting 4,000 other areas!

So fertilization is all about genetics while development is all about epigenetics. 

So if we have a mutation in one of these splicing enzymes or transcription factors, the kind of
changes that would result could well fit into the punctuated equilibrium (not gradual) model of
evolution. 
*** II
**** Randomness
DNA as the big boss man is undermined as we learn that 95% of the DNA is simply the instruction manual, that transcription
factors have huge roles especially in an if-then manner, that splicing and epigenetic effects impact
growth, and on and on. Here he highlights ways in which things are interconnected - environment,
genes, etc. In this area we move toward a way of thinking that seems to interest Sapolsky - the whole
chaos theory/Heisenberg Uncertainty Principle element of life in which there's a bit of randomness
and chance in even the most structured systems. And yet there's also a bit of structure in the
seemingly chaotic. This just might be an important theme in evolution...

As promoters change, transcription factors change. Splicing enzymes can change their behavior and
create entirely new proteins. Changes in transcription factors can activate entirely different gene
sequences. Little changes can have big results, especially when those changes cascade. 

Vasopressin and vols (and perhaps humans). One version of the promoter stimulates release of more
vasopressin. Correlated with this is an increase in monogamous mating. The more vasopressin, the
more likely the vol is to be monogamous. And polygamous vols, when given vasopressin, begin
behaving monogamously. There's some evidence that this impacts human behavior too. Sapolsky
mentions a study that suggested that the type of vasopressin promoter you have provided some
predictive power of the likelihood of you getting divorced down the line. Naturally there are three
million confounds here, but it gives one pause in terms of the concept of free will.

Dinorphin (pain receptor) promoters seem to relate to ease of addiction to pain killing drugs in rats.
The more promoters that the rat has for dinorphin, the more likely that rat is to exhibit addictive
behavior toward pain killing drugs when given the opportunity. 

Changing transcription factors changes gene networks. He notes that a disproportionate share of the
differences in the genetic code between chimps and humans lie in the genes that code for
transcription factors. This leads to the suggestion that the most interesting evolutionary changes are
going to be those found in changes in the regulatory structure of the genes, not in changes to the
DNA itself. 

The more genes you find in a species, the greater the percentage of those genes that code for
transcription factors. For example you have 1 gene, A, so there's 1 transcription factor. Have two
genes, A and B, and you now have 3 transcription factors - one for A, one for B and one for AB. And so
on down the line.

Microevolution is about the proteins; macroevolution is about the networks. 
**** Maegaret McClintock and transposones
She argued for transposable genes in plants, i.e. genes that are actually moving around on the DNA line, creating new proteins, networks,
results. This amazing feature is also seen in the human immune system which adapts itself
constantly in order to combat pathogenic invaders (and sometimes, unfortunately, to combat things
like the insulin production cells in the Islets of Langerhorn - giving the person Type I diabetes). A
plant can't run away from trouble, so it had to evolve another way to handle the world's difficulties.
So they have fancy stress response tricks, such as changing genes around to handle new
environments and challenges. 

This is done by activating transposaze, which is a splicing enzyme that slices out sections of the genes
so they can jump around. These types of genes are also seen in animals.
**** Antigenic Variations
Predictably, and unfortunately, pathogens also get to utilize this trick. Trypanosoma brucei is a nasty
protazoan that causes sleeping sickness in humans. It invade the body and in order to evade the
host's immune response, uses jumping genes to change its protein coating. So the adaptive immune
system stays a step behind it because just as soon as it figures out how to kill the original coating, the
trypanosoma has changed its shield. The adaptive immune system takes out pathogens in a sort of
lock and key function, but if the pathogen changes the locks faster than the immune system can
chisel out the keys, you're in for real trouble. 

This phenomenon is known as antigenic variation. In essence the pathogen has numerous shells (for
this parasite the estimate is in the thousands) and shuffles through them as it replicates itself. It puts
the immune system at a distinct disadvantage. Imagine you're a detective and you can only catch
your suspect if he's wearing the exact same outfit he had on when he committed the crime. If he has
1 shirt, 1 pair of pants and one pair of shoes, you'll catch him immediately. If he has 1 shirt, 1 pair of
pants and 2 shoes, it's going to take 2 days. If he has 15 shirts, 15 pairs of pants and 5 shoes, you're
eating donuts, drinking coffee and peeing in a Mountain Dew bottle for 1,125 days. If the suspect is
there to rob 25 liquor stores and 10 banks while you look for outfit #1, he's got a lot of time to get it
done. 

This happens elsewhere in the body. Neuroprogenitor cells can also jump around - this is neurons
moving around, this is the cells in your body that have the most to do with determining who you are
being the least constrained by genetic determinism. 
**** Autoimmune Disorders 
So a hormone has the two receptors on it - one on the hormone side to trigger it and other that
connects to the promoter. These can be mixed and matched so that a hormone can be triggered and
then go out and attach to an entirely new promoter. This is a new if-then clause. 

Glucocorticoids are stress hormones that suppress the immune system (there's a lot more to it, but
in brief, they suppress it by reducing the inflammatory response). A slight clip and a little shuffling
and you can create the new if-then clause if there's progesterone around suppress immunity. What's
this about? Pregnancy. This if-then statement prevents the immune system from attacking the fetus.

The downside is that when the immune system recovers, it sometimes overshoots the original mark
and ends up getting hyper. In its hyper state it's over-reactive and next thing you know you have an
auto-immune disease, which is more common after pregnancy. This can be dangerous and some
autoimmune disorders, such as lupus, are severe enough that the affected will be advised to avoid
pregnancy. 
**** Copy number variants
Next up are copy number variants. This is the world of multiple copies of the same gene. This can
allow for experimentation with one back-up copy. At the same time, there can be problems linked to
it, such as is seen with schizophrenia. The multiple copies of genes may account for "irreducible
complexity," i.e. how can an eye pop up out of nowhere? If the organism has multiple copies of
sensory genes and is able to experiment with one without sacrificing the other, it could develop a
feature incrementally, slowly growing an eye while using sound and tactile information for guidance
until such time as the eye starts working. (This can account for evolution's production of vision while
leaving a very big door open in regard to what's out there that we haven't evolved to see. This is the
whole world of intuition and spiritual belief. This is the whole world of wackos that claim they can
sense things others can't. Or is it?)
**** Bottlenecks
For the most part these changes will not be beneficial overall since they have to coordinate with so
many different gene networks. Therefore it's generally a stabilizing selection in which you won't see
much change. However, when the genes stumble onto something good, you may see a rapid
change.

Bottlenecks occur when particular traits enable a subset of the population to survive, regardless of
the problems with their other traits. He states cheetahs went through this. Sickle cell anemia is
another common example. 

In brief, the hominid body is designed to store nutrients. These days our food is loaded with all kinds of everything. So we're seeing a huge increase
in average body mass (folks are getting fatter) because the body is storing all the good and bad
stuff. The more wasteful your metabolism, the better it is. Get yourself a body that isn't used to a
western diet and you are a candidate for type II diabetes as your body grows beyond what it's
supposed to. The fat cells get full and start ignoring insulin. Insulin gets angry and calls on the
pancreas to make more insulin to help force the fat cells to do their job. The fat cells relent a little but
demand ever greater amount of insulin to listen and pretty soon you've got a blood sugar problem
and are well on your way to burning out your pancreas. 

The Dutch Hunger winter is a great example of this. Due to Nazi shuffling of food, the Dutch
experienced a winter of starvation. The women who were carrying babies gave birth to "thrifty"
babies whose metabolisms had learned to hold tightly onto whatever nutrients floated by. Thus they
are more at risk for all the metabolic problems in adulthood - hypertension, diabetes, excessive
weight gain, etc. And so are their offspring since they gestated within a mother's body that was very
thrifty and thus shared less nutrients. 

Sometimes there are surprising effects from genetic variation, such as the story of the silverfox.
**** Antibiotic Resistance
The last fear is that of antibiotic resistance. MRSA, VRE, smallpox, our friend trypanosoma, all with a
capacity to evolve faster than our drugs. So there's a continual battle between the cells of our body
and the pathogens that want to crash the party. 
